version: '3.7'
services:
  db:
    container_name: database
    image: mysql:8.0
    ports:
      - '3306:3306'
    restart: 'unless-stopped'
    environment:
      - MYSQL_ROOT_PASSWORD=hoplin1234!
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=dsc
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
