version: '3.7'
services:
  db:
    container_name: dsc-be-db
    image: mongo
    ports:
      - '27017:27017'
    restart: 'unless-stopped'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password1234!
      - MONGO_INITDB_DATABASE=dsc-be
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
