version: '3.7'
services:
  api:
    container_name: api-server
    build: .
    image: 'dsc-lab-be-api'
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    environment:
      - API_MODE=dev
    networks:
      - backend-network
    volumes:
      - '..:/api'
    depends_on:
      - db
      - mongo
  db:
    container_name: database
    image: mysql
    ports:
      - '3306:3306'
    restart: 'unless-stopped'
    environment:
      - MYSQL_ROOT_PASSWORD=hoplin1234!
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=dsc
    networks:
      - backend-network
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: 'unless-stopped'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password1234!
      - MONGO_INITDB_DATABASE=cloud-edu
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
